### GET request to example server
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "name": "shehan",
  "email": "content@gmail.com",
  "password": "Kaushalya4255#"
}

###
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "content@gmail.com",
  "password": "Kaushalya4255#"
}
